// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: controlplane/v1/alias.proto

package controlplanev1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Alias is the aggregate state for one model/route alias.
type Alias struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Scope         string                 `protobuf:"bytes,1,opt,name=scope,proto3" json:"scope,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Target        string                 `protobuf:"bytes,3,opt,name=target,proto3" json:"target,omitempty"`
	Params        map[string]string      `protobuf:"bytes,4,rep,name=params,proto3" json:"params,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Deleted       bool                   `protobuf:"varint,5,opt,name=deleted,proto3" json:"deleted,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Alias) Reset() {
	*x = Alias{}
	mi := &file_controlplane_v1_alias_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Alias) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Alias) ProtoMessage() {}

func (x *Alias) ProtoReflect() protoreflect.Message {
	mi := &file_controlplane_v1_alias_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Alias.ProtoReflect.Descriptor instead.
func (*Alias) Descriptor() ([]byte, []int) {
	return file_controlplane_v1_alias_proto_rawDescGZIP(), []int{0}
}

func (x *Alias) GetScope() string {
	if x != nil {
		return x.Scope
	}
	return ""
}

func (x *Alias) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Alias) GetTarget() string {
	if x != nil {
		return x.Target
	}
	return ""
}

func (x *Alias) GetParams() map[string]string {
	if x != nil {
		return x.Params
	}
	return nil
}

func (x *Alias) GetDeleted() bool {
	if x != nil {
		return x.Deleted
	}
	return false
}

type SetAlias struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Target        string                 `protobuf:"bytes,1,opt,name=target,proto3" json:"target,omitempty"`
	Params        map[string]string      `protobuf:"bytes,2,rep,name=params,proto3" json:"params,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetAlias) Reset() {
	*x = SetAlias{}
	mi := &file_controlplane_v1_alias_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetAlias) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetAlias) ProtoMessage() {}

func (x *SetAlias) ProtoReflect() protoreflect.Message {
	mi := &file_controlplane_v1_alias_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetAlias.ProtoReflect.Descriptor instead.
func (*SetAlias) Descriptor() ([]byte, []int) {
	return file_controlplane_v1_alias_proto_rawDescGZIP(), []int{1}
}

func (x *SetAlias) GetTarget() string {
	if x != nil {
		return x.Target
	}
	return ""
}

func (x *SetAlias) GetParams() map[string]string {
	if x != nil {
		return x.Params
	}
	return nil
}

type DeleteAlias struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteAlias) Reset() {
	*x = DeleteAlias{}
	mi := &file_controlplane_v1_alias_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteAlias) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteAlias) ProtoMessage() {}

func (x *DeleteAlias) ProtoReflect() protoreflect.Message {
	mi := &file_controlplane_v1_alias_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteAlias.ProtoReflect.Descriptor instead.
func (*DeleteAlias) Descriptor() ([]byte, []int) {
	return file_controlplane_v1_alias_proto_rawDescGZIP(), []int{2}
}

type AliasCommand struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Kind:
	//
	//	*AliasCommand_Set
	//	*AliasCommand_Delete
	Kind          isAliasCommand_Kind `protobuf_oneof:"kind"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AliasCommand) Reset() {
	*x = AliasCommand{}
	mi := &file_controlplane_v1_alias_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AliasCommand) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AliasCommand) ProtoMessage() {}

func (x *AliasCommand) ProtoReflect() protoreflect.Message {
	mi := &file_controlplane_v1_alias_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AliasCommand.ProtoReflect.Descriptor instead.
func (*AliasCommand) Descriptor() ([]byte, []int) {
	return file_controlplane_v1_alias_proto_rawDescGZIP(), []int{3}
}

func (x *AliasCommand) GetKind() isAliasCommand_Kind {
	if x != nil {
		return x.Kind
	}
	return nil
}

func (x *AliasCommand) GetSet() *SetAlias {
	if x != nil {
		if x, ok := x.Kind.(*AliasCommand_Set); ok {
			return x.Set
		}
	}
	return nil
}

func (x *AliasCommand) GetDelete() *DeleteAlias {
	if x != nil {
		if x, ok := x.Kind.(*AliasCommand_Delete); ok {
			return x.Delete
		}
	}
	return nil
}

type isAliasCommand_Kind interface {
	isAliasCommand_Kind()
}

type AliasCommand_Set struct {
	Set *SetAlias `protobuf:"bytes,1,opt,name=set,proto3,oneof"`
}

type AliasCommand_Delete struct {
	Delete *DeleteAlias `protobuf:"bytes,2,opt,name=delete,proto3,oneof"`
}

func (*AliasCommand_Set) isAliasCommand_Kind() {}

func (*AliasCommand_Delete) isAliasCommand_Kind() {}

type AliasSet struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Target        string                 `protobuf:"bytes,1,opt,name=target,proto3" json:"target,omitempty"`
	Params        map[string]string      `protobuf:"bytes,2,rep,name=params,proto3" json:"params,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AliasSet) Reset() {
	*x = AliasSet{}
	mi := &file_controlplane_v1_alias_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AliasSet) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AliasSet) ProtoMessage() {}

func (x *AliasSet) ProtoReflect() protoreflect.Message {
	mi := &file_controlplane_v1_alias_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AliasSet.ProtoReflect.Descriptor instead.
func (*AliasSet) Descriptor() ([]byte, []int) {
	return file_controlplane_v1_alias_proto_rawDescGZIP(), []int{4}
}

func (x *AliasSet) GetTarget() string {
	if x != nil {
		return x.Target
	}
	return ""
}

func (x *AliasSet) GetParams() map[string]string {
	if x != nil {
		return x.Params
	}
	return nil
}

type AliasDeleted struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AliasDeleted) Reset() {
	*x = AliasDeleted{}
	mi := &file_controlplane_v1_alias_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AliasDeleted) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AliasDeleted) ProtoMessage() {}

func (x *AliasDeleted) ProtoReflect() protoreflect.Message {
	mi := &file_controlplane_v1_alias_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AliasDeleted.ProtoReflect.Descriptor instead.
func (*AliasDeleted) Descriptor() ([]byte, []int) {
	return file_controlplane_v1_alias_proto_rawDescGZIP(), []int{5}
}

type AliasEvent struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Kind:
	//
	//	*AliasEvent_Set
	//	*AliasEvent_Deleted
	Kind          isAliasEvent_Kind `protobuf_oneof:"kind"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AliasEvent) Reset() {
	*x = AliasEvent{}
	mi := &file_controlplane_v1_alias_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AliasEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AliasEvent) ProtoMessage() {}

func (x *AliasEvent) ProtoReflect() protoreflect.Message {
	mi := &file_controlplane_v1_alias_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AliasEvent.ProtoReflect.Descriptor instead.
func (*AliasEvent) Descriptor() ([]byte, []int) {
	return file_controlplane_v1_alias_proto_rawDescGZIP(), []int{6}
}

func (x *AliasEvent) GetKind() isAliasEvent_Kind {
	if x != nil {
		return x.Kind
	}
	return nil
}

func (x *AliasEvent) GetSet() *AliasSet {
	if x != nil {
		if x, ok := x.Kind.(*AliasEvent_Set); ok {
			return x.Set
		}
	}
	return nil
}

func (x *AliasEvent) GetDeleted() *AliasDeleted {
	if x != nil {
		if x, ok := x.Kind.(*AliasEvent_Deleted); ok {
			return x.Deleted
		}
	}
	return nil
}

type isAliasEvent_Kind interface {
	isAliasEvent_Kind()
}

type AliasEvent_Set struct {
	Set *AliasSet `protobuf:"bytes,1,opt,name=set,proto3,oneof"`
}

type AliasEvent_Deleted struct {
	Deleted *AliasDeleted `protobuf:"bytes,2,opt,name=deleted,proto3,oneof"`
}

func (*AliasEvent_Set) isAliasEvent_Kind() {}

func (*AliasEvent_Deleted) isAliasEvent_Kind() {}

var File_controlplane_v1_alias_proto protoreflect.FileDescriptor

const file_controlplane_v1_alias_proto_rawDesc = "" +
	"\n" +
	"\x1bcontrolplane/v1/alias.proto\x12\x0fcontrolplane.v1\"\xda\x01\n" +
	"\x05Alias\x12\x14\n" +
	"\x05scope\x18\x01 \x01(\tR\x05scope\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x16\n" +
	"\x06target\x18\x03 \x01(\tR\x06target\x12:\n" +
	"\x06params\x18\x04 \x03(\v2\".controlplane.v1.Alias.ParamsEntryR\x06params\x12\x18\n" +
	"\adeleted\x18\x05 \x01(\bR\adeleted\x1a9\n" +
	"\vParamsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x9c\x01\n" +
	"\bSetAlias\x12\x16\n" +
	"\x06target\x18\x01 \x01(\tR\x06target\x12=\n" +
	"\x06params\x18\x02 \x03(\v2%.controlplane.v1.SetAlias.ParamsEntryR\x06params\x1a9\n" +
	"\vParamsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\r\n" +
	"\vDeleteAlias\"}\n" +
	"\fAliasCommand\x12-\n" +
	"\x03set\x18\x01 \x01(\v2\x19.controlplane.v1.SetAliasH\x00R\x03set\x126\n" +
	"\x06delete\x18\x02 \x01(\v2\x1c.controlplane.v1.DeleteAliasH\x00R\x06deleteB\x06\n" +
	"\x04kind\"\x9c\x01\n" +
	"\bAliasSet\x12\x16\n" +
	"\x06target\x18\x01 \x01(\tR\x06target\x12=\n" +
	"\x06params\x18\x02 \x03(\v2%.controlplane.v1.AliasSet.ParamsEntryR\x06params\x1a9\n" +
	"\vParamsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x0e\n" +
	"\fAliasDeleted\"~\n" +
	"\n" +
	"AliasEvent\x12-\n" +
	"\x03set\x18\x01 \x01(\v2\x19.controlplane.v1.AliasSetH\x00R\x03set\x129\n" +
	"\adeleted\x18\x02 \x01(\v2\x1d.controlplane.v1.AliasDeletedH\x00R\adeletedB\x06\n" +
	"\x04kindBAZ?github.com/laenenai/inferbus/api/controlplane/v1;controlplanev1b\x06proto3"

var (
	file_controlplane_v1_alias_proto_rawDescOnce sync.Once
	file_controlplane_v1_alias_proto_rawDescData []byte
)

func file_controlplane_v1_alias_proto_rawDescGZIP() []byte {
	file_controlplane_v1_alias_proto_rawDescOnce.Do(func() {
		file_controlplane_v1_alias_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_controlplane_v1_alias_proto_rawDesc), len(file_controlplane_v1_alias_proto_rawDesc)))
	})
	return file_controlplane_v1_alias_proto_rawDescData
}

var file_controlplane_v1_alias_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_controlplane_v1_alias_proto_goTypes = []any{
	(*Alias)(nil),        // 0: controlplane.v1.Alias
	(*SetAlias)(nil),     // 1: controlplane.v1.SetAlias
	(*DeleteAlias)(nil),  // 2: controlplane.v1.DeleteAlias
	(*AliasCommand)(nil), // 3: controlplane.v1.AliasCommand
	(*AliasSet)(nil),     // 4: controlplane.v1.AliasSet
	(*AliasDeleted)(nil), // 5: controlplane.v1.AliasDeleted
	(*AliasEvent)(nil),   // 6: controlplane.v1.AliasEvent
	nil,                  // 7: controlplane.v1.Alias.ParamsEntry
	nil,                  // 8: controlplane.v1.SetAlias.ParamsEntry
	nil,                  // 9: controlplane.v1.AliasSet.ParamsEntry
}
var file_controlplane_v1_alias_proto_depIdxs = []int32{
	7, // 0: controlplane.v1.Alias.params:type_name -> controlplane.v1.Alias.ParamsEntry
	8, // 1: controlplane.v1.SetAlias.params:type_name -> controlplane.v1.SetAlias.ParamsEntry
	1, // 2: controlplane.v1.AliasCommand.set:type_name -> controlplane.v1.SetAlias
	2, // 3: controlplane.v1.AliasCommand.delete:type_name -> controlplane.v1.DeleteAlias
	9, // 4: controlplane.v1.AliasSet.params:type_name -> controlplane.v1.AliasSet.ParamsEntry
	4, // 5: controlplane.v1.AliasEvent.set:type_name -> controlplane.v1.AliasSet
	5, // 6: controlplane.v1.AliasEvent.deleted:type_name -> controlplane.v1.AliasDeleted
	7, // [7:7] is the sub-list for method output_type
	7, // [7:7] is the sub-list for method input_type
	7, // [7:7] is the sub-list for extension type_name
	7, // [7:7] is the sub-list for extension extendee
	0, // [0:7] is the sub-list for field type_name
}

func init() { file_controlplane_v1_alias_proto_init() }
func file_controlplane_v1_alias_proto_init() {
	if File_controlplane_v1_alias_proto != nil {
		return
	}
	file_controlplane_v1_alias_proto_msgTypes[3].OneofWrappers = []any{
		(*AliasCommand_Set)(nil),
		(*AliasCommand_Delete)(nil),
	}
	file_controlplane_v1_alias_proto_msgTypes[6].OneofWrappers = []any{
		(*AliasEvent_Set)(nil),
		(*AliasEvent_Deleted)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_controlplane_v1_alias_proto_rawDesc), len(file_controlplane_v1_alias_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_controlplane_v1_alias_proto_goTypes,
		DependencyIndexes: file_controlplane_v1_alias_proto_depIdxs,
		MessageInfos:      file_controlplane_v1_alias_proto_msgTypes,
	}.Build()
	File_controlplane_v1_alias_proto = out.File
	file_controlplane_v1_alias_proto_goTypes = nil
	file_controlplane_v1_alias_proto_depIdxs = nil
}
