// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: controlplane/v1/apikey.proto

package controlplanev1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ApiKey is the aggregate state for one API key.
type ApiKey struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	Id                 string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Org                string                 `protobuf:"bytes,2,opt,name=org,proto3" json:"org,omitempty"`
	Project            string                 `protobuf:"bytes,3,opt,name=project,proto3" json:"project,omitempty"`
	Name               string                 `protobuf:"bytes,4,opt,name=name,proto3" json:"name,omitempty"`
	Hash               string                 `protobuf:"bytes,5,opt,name=hash,proto3" json:"hash,omitempty"`
	Allow              []string               `protobuf:"bytes,6,rep,name=allow,proto3" json:"allow,omitempty"`
	RateLimitRpm       int32                  `protobuf:"varint,7,opt,name=rate_limit_rpm,json=rateLimitRpm,proto3" json:"rate_limit_rpm,omitempty"`
	MonthlyTokenBudget int64                  `protobuf:"varint,8,opt,name=monthly_token_budget,json=monthlyTokenBudget,proto3" json:"monthly_token_budget,omitempty"`
	Disabled           bool                   `protobuf:"varint,9,opt,name=disabled,proto3" json:"disabled,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *ApiKey) Reset() {
	*x = ApiKey{}
	mi := &file_controlplane_v1_apikey_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApiKey) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApiKey) ProtoMessage() {}

func (x *ApiKey) ProtoReflect() protoreflect.Message {
	mi := &file_controlplane_v1_apikey_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApiKey.ProtoReflect.Descriptor instead.
func (*ApiKey) Descriptor() ([]byte, []int) {
	return file_controlplane_v1_apikey_proto_rawDescGZIP(), []int{0}
}

func (x *ApiKey) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ApiKey) GetOrg() string {
	if x != nil {
		return x.Org
	}
	return ""
}

func (x *ApiKey) GetProject() string {
	if x != nil {
		return x.Project
	}
	return ""
}

func (x *ApiKey) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ApiKey) GetHash() string {
	if x != nil {
		return x.Hash
	}
	return ""
}

func (x *ApiKey) GetAllow() []string {
	if x != nil {
		return x.Allow
	}
	return nil
}

func (x *ApiKey) GetRateLimitRpm() int32 {
	if x != nil {
		return x.RateLimitRpm
	}
	return 0
}

func (x *ApiKey) GetMonthlyTokenBudget() int64 {
	if x != nil {
		return x.MonthlyTokenBudget
	}
	return 0
}

func (x *ApiKey) GetDisabled() bool {
	if x != nil {
		return x.Disabled
	}
	return false
}

type CreateKey struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	Id                 string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Org                string                 `protobuf:"bytes,2,opt,name=org,proto3" json:"org,omitempty"`
	Project            string                 `protobuf:"bytes,3,opt,name=project,proto3" json:"project,omitempty"`
	Name               string                 `protobuf:"bytes,4,opt,name=name,proto3" json:"name,omitempty"`
	Hash               string                 `protobuf:"bytes,5,opt,name=hash,proto3" json:"hash,omitempty"`
	Allow              []string               `protobuf:"bytes,6,rep,name=allow,proto3" json:"allow,omitempty"`
	RateLimitRpm       int32                  `protobuf:"varint,7,opt,name=rate_limit_rpm,json=rateLimitRpm,proto3" json:"rate_limit_rpm,omitempty"`
	MonthlyTokenBudget int64                  `protobuf:"varint,8,opt,name=monthly_token_budget,json=monthlyTokenBudget,proto3" json:"monthly_token_budget,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *CreateKey) Reset() {
	*x = CreateKey{}
	mi := &file_controlplane_v1_apikey_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateKey) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateKey) ProtoMessage() {}

func (x *CreateKey) ProtoReflect() protoreflect.Message {
	mi := &file_controlplane_v1_apikey_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateKey.ProtoReflect.Descriptor instead.
func (*CreateKey) Descriptor() ([]byte, []int) {
	return file_controlplane_v1_apikey_proto_rawDescGZIP(), []int{1}
}

func (x *CreateKey) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *CreateKey) GetOrg() string {
	if x != nil {
		return x.Org
	}
	return ""
}

func (x *CreateKey) GetProject() string {
	if x != nil {
		return x.Project
	}
	return ""
}

func (x *CreateKey) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateKey) GetHash() string {
	if x != nil {
		return x.Hash
	}
	return ""
}

func (x *CreateKey) GetAllow() []string {
	if x != nil {
		return x.Allow
	}
	return nil
}

func (x *CreateKey) GetRateLimitRpm() int32 {
	if x != nil {
		return x.RateLimitRpm
	}
	return 0
}

func (x *CreateKey) GetMonthlyTokenBudget() int64 {
	if x != nil {
		return x.MonthlyTokenBudget
	}
	return 0
}

type RotateKey struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NewHash       string                 `protobuf:"bytes,1,opt,name=new_hash,json=newHash,proto3" json:"new_hash,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RotateKey) Reset() {
	*x = RotateKey{}
	mi := &file_controlplane_v1_apikey_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RotateKey) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RotateKey) ProtoMessage() {}

func (x *RotateKey) ProtoReflect() protoreflect.Message {
	mi := &file_controlplane_v1_apikey_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RotateKey.ProtoReflect.Descriptor instead.
func (*RotateKey) Descriptor() ([]byte, []int) {
	return file_controlplane_v1_apikey_proto_rawDescGZIP(), []int{2}
}

func (x *RotateKey) GetNewHash() string {
	if x != nil {
		return x.NewHash
	}
	return ""
}

type DisableKey struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DisableKey) Reset() {
	*x = DisableKey{}
	mi := &file_controlplane_v1_apikey_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DisableKey) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DisableKey) ProtoMessage() {}

func (x *DisableKey) ProtoReflect() protoreflect.Message {
	mi := &file_controlplane_v1_apikey_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DisableKey.ProtoReflect.Descriptor instead.
func (*DisableKey) Descriptor() ([]byte, []int) {
	return file_controlplane_v1_apikey_proto_rawDescGZIP(), []int{3}
}

type SetAllowlist struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Allow         []string               `protobuf:"bytes,1,rep,name=allow,proto3" json:"allow,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetAllowlist) Reset() {
	*x = SetAllowlist{}
	mi := &file_controlplane_v1_apikey_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetAllowlist) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetAllowlist) ProtoMessage() {}

func (x *SetAllowlist) ProtoReflect() protoreflect.Message {
	mi := &file_controlplane_v1_apikey_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetAllowlist.ProtoReflect.Descriptor instead.
func (*SetAllowlist) Descriptor() ([]byte, []int) {
	return file_controlplane_v1_apikey_proto_rawDescGZIP(), []int{4}
}

func (x *SetAllowlist) GetAllow() []string {
	if x != nil {
		return x.Allow
	}
	return nil
}

type SetLimits struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	RateLimitRpm       int32                  `protobuf:"varint,1,opt,name=rate_limit_rpm,json=rateLimitRpm,proto3" json:"rate_limit_rpm,omitempty"`
	MonthlyTokenBudget int64                  `protobuf:"varint,2,opt,name=monthly_token_budget,json=monthlyTokenBudget,proto3" json:"monthly_token_budget,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *SetLimits) Reset() {
	*x = SetLimits{}
	mi := &file_controlplane_v1_apikey_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetLimits) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetLimits) ProtoMessage() {}

func (x *SetLimits) ProtoReflect() protoreflect.Message {
	mi := &file_controlplane_v1_apikey_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetLimits.ProtoReflect.Descriptor instead.
func (*SetLimits) Descriptor() ([]byte, []int) {
	return file_controlplane_v1_apikey_proto_rawDescGZIP(), []int{5}
}

func (x *SetLimits) GetRateLimitRpm() int32 {
	if x != nil {
		return x.RateLimitRpm
	}
	return 0
}

func (x *SetLimits) GetMonthlyTokenBudget() int64 {
	if x != nil {
		return x.MonthlyTokenBudget
	}
	return 0
}

type ApiKeyCommand struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Kind:
	//
	//	*ApiKeyCommand_Create
	//	*ApiKeyCommand_Rotate
	//	*ApiKeyCommand_Disable
	//	*ApiKeyCommand_SetAllowlist
	//	*ApiKeyCommand_SetLimits
	Kind          isApiKeyCommand_Kind `protobuf_oneof:"kind"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ApiKeyCommand) Reset() {
	*x = ApiKeyCommand{}
	mi := &file_controlplane_v1_apikey_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApiKeyCommand) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApiKeyCommand) ProtoMessage() {}

func (x *ApiKeyCommand) ProtoReflect() protoreflect.Message {
	mi := &file_controlplane_v1_apikey_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApiKeyCommand.ProtoReflect.Descriptor instead.
func (*ApiKeyCommand) Descriptor() ([]byte, []int) {
	return file_controlplane_v1_apikey_proto_rawDescGZIP(), []int{6}
}

func (x *ApiKeyCommand) GetKind() isApiKeyCommand_Kind {
	if x != nil {
		return x.Kind
	}
	return nil
}

func (x *ApiKeyCommand) GetCreate() *CreateKey {
	if x != nil {
		if x, ok := x.Kind.(*ApiKeyCommand_Create); ok {
			return x.Create
		}
	}
	return nil
}

func (x *ApiKeyCommand) GetRotate() *RotateKey {
	if x != nil {
		if x, ok := x.Kind.(*ApiKeyCommand_Rotate); ok {
			return x.Rotate
		}
	}
	return nil
}

func (x *ApiKeyCommand) GetDisable() *DisableKey {
	if x != nil {
		if x, ok := x.Kind.(*ApiKeyCommand_Disable); ok {
			return x.Disable
		}
	}
	return nil
}

func (x *ApiKeyCommand) GetSetAllowlist() *SetAllowlist {
	if x != nil {
		if x, ok := x.Kind.(*ApiKeyCommand_SetAllowlist); ok {
			return x.SetAllowlist
		}
	}
	return nil
}

func (x *ApiKeyCommand) GetSetLimits() *SetLimits {
	if x != nil {
		if x, ok := x.Kind.(*ApiKeyCommand_SetLimits); ok {
			return x.SetLimits
		}
	}
	return nil
}

type isApiKeyCommand_Kind interface {
	isApiKeyCommand_Kind()
}

type ApiKeyCommand_Create struct {
	Create *CreateKey `protobuf:"bytes,1,opt,name=create,proto3,oneof"`
}

type ApiKeyCommand_Rotate struct {
	Rotate *RotateKey `protobuf:"bytes,2,opt,name=rotate,proto3,oneof"`
}

type ApiKeyCommand_Disable struct {
	Disable *DisableKey `protobuf:"bytes,3,opt,name=disable,proto3,oneof"`
}

type ApiKeyCommand_SetAllowlist struct {
	SetAllowlist *SetAllowlist `protobuf:"bytes,4,opt,name=set_allowlist,json=setAllowlist,proto3,oneof"`
}

type ApiKeyCommand_SetLimits struct {
	SetLimits *SetLimits `protobuf:"bytes,5,opt,name=set_limits,json=setLimits,proto3,oneof"`
}

func (*ApiKeyCommand_Create) isApiKeyCommand_Kind() {}

func (*ApiKeyCommand_Rotate) isApiKeyCommand_Kind() {}

func (*ApiKeyCommand_Disable) isApiKeyCommand_Kind() {}

func (*ApiKeyCommand_SetAllowlist) isApiKeyCommand_Kind() {}

func (*ApiKeyCommand_SetLimits) isApiKeyCommand_Kind() {}

type KeyCreated struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	Id                 string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Org                string                 `protobuf:"bytes,2,opt,name=org,proto3" json:"org,omitempty"`
	Project            string                 `protobuf:"bytes,3,opt,name=project,proto3" json:"project,omitempty"`
	Name               string                 `protobuf:"bytes,4,opt,name=name,proto3" json:"name,omitempty"`
	Hash               string                 `protobuf:"bytes,5,opt,name=hash,proto3" json:"hash,omitempty"`
	Allow              []string               `protobuf:"bytes,6,rep,name=allow,proto3" json:"allow,omitempty"`
	RateLimitRpm       int32                  `protobuf:"varint,7,opt,name=rate_limit_rpm,json=rateLimitRpm,proto3" json:"rate_limit_rpm,omitempty"`
	MonthlyTokenBudget int64                  `protobuf:"varint,8,opt,name=monthly_token_budget,json=monthlyTokenBudget,proto3" json:"monthly_token_budget,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *KeyCreated) Reset() {
	*x = KeyCreated{}
	mi := &file_controlplane_v1_apikey_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KeyCreated) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KeyCreated) ProtoMessage() {}

func (x *KeyCreated) ProtoReflect() protoreflect.Message {
	mi := &file_controlplane_v1_apikey_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KeyCreated.ProtoReflect.Descriptor instead.
func (*KeyCreated) Descriptor() ([]byte, []int) {
	return file_controlplane_v1_apikey_proto_rawDescGZIP(), []int{7}
}

func (x *KeyCreated) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *KeyCreated) GetOrg() string {
	if x != nil {
		return x.Org
	}
	return ""
}

func (x *KeyCreated) GetProject() string {
	if x != nil {
		return x.Project
	}
	return ""
}

func (x *KeyCreated) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *KeyCreated) GetHash() string {
	if x != nil {
		return x.Hash
	}
	return ""
}

func (x *KeyCreated) GetAllow() []string {
	if x != nil {
		return x.Allow
	}
	return nil
}

func (x *KeyCreated) GetRateLimitRpm() int32 {
	if x != nil {
		return x.RateLimitRpm
	}
	return 0
}

func (x *KeyCreated) GetMonthlyTokenBudget() int64 {
	if x != nil {
		return x.MonthlyTokenBudget
	}
	return 0
}

// KeyRotated carries the retired hash (spec §2), never the plaintext.
type KeyRotated struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NewHash       string                 `protobuf:"bytes,1,opt,name=new_hash,json=newHash,proto3" json:"new_hash,omitempty"`
	PreviousHash  string                 `protobuf:"bytes,2,opt,name=previous_hash,json=previousHash,proto3" json:"previous_hash,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *KeyRotated) Reset() {
	*x = KeyRotated{}
	mi := &file_controlplane_v1_apikey_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KeyRotated) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KeyRotated) ProtoMessage() {}

func (x *KeyRotated) ProtoReflect() protoreflect.Message {
	mi := &file_controlplane_v1_apikey_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KeyRotated.ProtoReflect.Descriptor instead.
func (*KeyRotated) Descriptor() ([]byte, []int) {
	return file_controlplane_v1_apikey_proto_rawDescGZIP(), []int{8}
}

func (x *KeyRotated) GetNewHash() string {
	if x != nil {
		return x.NewHash
	}
	return ""
}

func (x *KeyRotated) GetPreviousHash() string {
	if x != nil {
		return x.PreviousHash
	}
	return ""
}

// KeyDisabled carries the retired (current-at-time-of-disable) hash (spec §2).
type KeyDisabled struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CurrentHash   string                 `protobuf:"bytes,1,opt,name=current_hash,json=currentHash,proto3" json:"current_hash,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *KeyDisabled) Reset() {
	*x = KeyDisabled{}
	mi := &file_controlplane_v1_apikey_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KeyDisabled) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KeyDisabled) ProtoMessage() {}

func (x *KeyDisabled) ProtoReflect() protoreflect.Message {
	mi := &file_controlplane_v1_apikey_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KeyDisabled.ProtoReflect.Descriptor instead.
func (*KeyDisabled) Descriptor() ([]byte, []int) {
	return file_controlplane_v1_apikey_proto_rawDescGZIP(), []int{9}
}

func (x *KeyDisabled) GetCurrentHash() string {
	if x != nil {
		return x.CurrentHash
	}
	return ""
}

type KeyAllowlistChanged struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Allow         []string               `protobuf:"bytes,1,rep,name=allow,proto3" json:"allow,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *KeyAllowlistChanged) Reset() {
	*x = KeyAllowlistChanged{}
	mi := &file_controlplane_v1_apikey_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KeyAllowlistChanged) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KeyAllowlistChanged) ProtoMessage() {}

func (x *KeyAllowlistChanged) ProtoReflect() protoreflect.Message {
	mi := &file_controlplane_v1_apikey_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KeyAllowlistChanged.ProtoReflect.Descriptor instead.
func (*KeyAllowlistChanged) Descriptor() ([]byte, []int) {
	return file_controlplane_v1_apikey_proto_rawDescGZIP(), []int{10}
}

func (x *KeyAllowlistChanged) GetAllow() []string {
	if x != nil {
		return x.Allow
	}
	return nil
}

type KeyLimitsChanged struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	RateLimitRpm       int32                  `protobuf:"varint,1,opt,name=rate_limit_rpm,json=rateLimitRpm,proto3" json:"rate_limit_rpm,omitempty"`
	MonthlyTokenBudget int64                  `protobuf:"varint,2,opt,name=monthly_token_budget,json=monthlyTokenBudget,proto3" json:"monthly_token_budget,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *KeyLimitsChanged) Reset() {
	*x = KeyLimitsChanged{}
	mi := &file_controlplane_v1_apikey_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KeyLimitsChanged) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KeyLimitsChanged) ProtoMessage() {}

func (x *KeyLimitsChanged) ProtoReflect() protoreflect.Message {
	mi := &file_controlplane_v1_apikey_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KeyLimitsChanged.ProtoReflect.Descriptor instead.
func (*KeyLimitsChanged) Descriptor() ([]byte, []int) {
	return file_controlplane_v1_apikey_proto_rawDescGZIP(), []int{11}
}

func (x *KeyLimitsChanged) GetRateLimitRpm() int32 {
	if x != nil {
		return x.RateLimitRpm
	}
	return 0
}

func (x *KeyLimitsChanged) GetMonthlyTokenBudget() int64 {
	if x != nil {
		return x.MonthlyTokenBudget
	}
	return 0
}

type ApiKeyEvent struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Kind:
	//
	//	*ApiKeyEvent_Created
	//	*ApiKeyEvent_Rotated
	//	*ApiKeyEvent_Disabled
	//	*ApiKeyEvent_AllowlistChanged
	//	*ApiKeyEvent_LimitsChanged
	Kind          isApiKeyEvent_Kind `protobuf_oneof:"kind"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ApiKeyEvent) Reset() {
	*x = ApiKeyEvent{}
	mi := &file_controlplane_v1_apikey_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApiKeyEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApiKeyEvent) ProtoMessage() {}

func (x *ApiKeyEvent) ProtoReflect() protoreflect.Message {
	mi := &file_controlplane_v1_apikey_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApiKeyEvent.ProtoReflect.Descriptor instead.
func (*ApiKeyEvent) Descriptor() ([]byte, []int) {
	return file_controlplane_v1_apikey_proto_rawDescGZIP(), []int{12}
}

func (x *ApiKeyEvent) GetKind() isApiKeyEvent_Kind {
	if x != nil {
		return x.Kind
	}
	return nil
}

func (x *ApiKeyEvent) GetCreated() *KeyCreated {
	if x != nil {
		if x, ok := x.Kind.(*ApiKeyEvent_Created); ok {
			return x.Created
		}
	}
	return nil
}

func (x *ApiKeyEvent) GetRotated() *KeyRotated {
	if x != nil {
		if x, ok := x.Kind.(*ApiKeyEvent_Rotated); ok {
			return x.Rotated
		}
	}
	return nil
}

func (x *ApiKeyEvent) GetDisabled() *KeyDisabled {
	if x != nil {
		if x, ok := x.Kind.(*ApiKeyEvent_Disabled); ok {
			return x.Disabled
		}
	}
	return nil
}

func (x *ApiKeyEvent) GetAllowlistChanged() *KeyAllowlistChanged {
	if x != nil {
		if x, ok := x.Kind.(*ApiKeyEvent_AllowlistChanged); ok {
			return x.AllowlistChanged
		}
	}
	return nil
}

func (x *ApiKeyEvent) GetLimitsChanged() *KeyLimitsChanged {
	if x != nil {
		if x, ok := x.Kind.(*ApiKeyEvent_LimitsChanged); ok {
			return x.LimitsChanged
		}
	}
	return nil
}

type isApiKeyEvent_Kind interface {
	isApiKeyEvent_Kind()
}

type ApiKeyEvent_Created struct {
	Created *KeyCreated `protobuf:"bytes,1,opt,name=created,proto3,oneof"`
}

type ApiKeyEvent_Rotated struct {
	Rotated *KeyRotated `protobuf:"bytes,2,opt,name=rotated,proto3,oneof"`
}

type ApiKeyEvent_Disabled struct {
	Disabled *KeyDisabled `protobuf:"bytes,3,opt,name=disabled,proto3,oneof"`
}

type ApiKeyEvent_AllowlistChanged struct {
	AllowlistChanged *KeyAllowlistChanged `protobuf:"bytes,4,opt,name=allowlist_changed,json=allowlistChanged,proto3,oneof"`
}

type ApiKeyEvent_LimitsChanged struct {
	LimitsChanged *KeyLimitsChanged `protobuf:"bytes,5,opt,name=limits_changed,json=limitsChanged,proto3,oneof"`
}

func (*ApiKeyEvent_Created) isApiKeyEvent_Kind() {}

func (*ApiKeyEvent_Rotated) isApiKeyEvent_Kind() {}

func (*ApiKeyEvent_Disabled) isApiKeyEvent_Kind() {}

func (*ApiKeyEvent_AllowlistChanged) isApiKeyEvent_Kind() {}

func (*ApiKeyEvent_LimitsChanged) isApiKeyEvent_Kind() {}

var File_controlplane_v1_apikey_proto protoreflect.FileDescriptor

const file_controlplane_v1_apikey_proto_rawDesc = "" +
	"\n" +
	"\x1ccontrolplane/v1/apikey.proto\x12\x0fcontrolplane.v1\"\xf6\x01\n" +
	"\x06ApiKey\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x10\n" +
	"\x03org\x18\x02 \x01(\tR\x03org\x12\x18\n" +
	"\aproject\x18\x03 \x01(\tR\aproject\x12\x12\n" +
	"\x04name\x18\x04 \x01(\tR\x04name\x12\x12\n" +
	"\x04hash\x18\x05 \x01(\tR\x04hash\x12\x14\n" +
	"\x05allow\x18\x06 \x03(\tR\x05allow\x12$\n" +
	"\x0erate_limit_rpm\x18\a \x01(\x05R\frateLimitRpm\x120\n" +
	"\x14monthly_token_budget\x18\b \x01(\x03R\x12monthlyTokenBudget\x12\x1a\n" +
	"\bdisabled\x18\t \x01(\bR\bdisabled\"\xdd\x01\n" +
	"\tCreateKey\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x10\n" +
	"\x03org\x18\x02 \x01(\tR\x03org\x12\x18\n" +
	"\aproject\x18\x03 \x01(\tR\aproject\x12\x12\n" +
	"\x04name\x18\x04 \x01(\tR\x04name\x12\x12\n" +
	"\x04hash\x18\x05 \x01(\tR\x04hash\x12\x14\n" +
	"\x05allow\x18\x06 \x03(\tR\x05allow\x12$\n" +
	"\x0erate_limit_rpm\x18\a \x01(\x05R\frateLimitRpm\x120\n" +
	"\x14monthly_token_budget\x18\b \x01(\x03R\x12monthlyTokenBudget\"&\n" +
	"\tRotateKey\x12\x19\n" +
	"\bnew_hash\x18\x01 \x01(\tR\anewHash\"\f\n" +
	"\n" +
	"DisableKey\"$\n" +
	"\fSetAllowlist\x12\x14\n" +
	"\x05allow\x18\x01 \x03(\tR\x05allow\"c\n" +
	"\tSetLimits\x12$\n" +
	"\x0erate_limit_rpm\x18\x01 \x01(\x05R\frateLimitRpm\x120\n" +
	"\x14monthly_token_budget\x18\x02 \x01(\x03R\x12monthlyTokenBudget\"\xbf\x02\n" +
	"\rApiKeyCommand\x124\n" +
	"\x06create\x18\x01 \x01(\v2\x1a.controlplane.v1.CreateKeyH\x00R\x06create\x124\n" +
	"\x06rotate\x18\x02 \x01(\v2\x1a.controlplane.v1.RotateKeyH\x00R\x06rotate\x127\n" +
	"\adisable\x18\x03 \x01(\v2\x1b.controlplane.v1.DisableKeyH\x00R\adisable\x12D\n" +
	"\rset_allowlist\x18\x04 \x01(\v2\x1d.controlplane.v1.SetAllowlistH\x00R\fsetAllowlist\x12;\n" +
	"\n" +
	"set_limits\x18\x05 \x01(\v2\x1a.controlplane.v1.SetLimitsH\x00R\tsetLimitsB\x06\n" +
	"\x04kind\"\xde\x01\n" +
	"\n" +
	"KeyCreated\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x10\n" +
	"\x03org\x18\x02 \x01(\tR\x03org\x12\x18\n" +
	"\aproject\x18\x03 \x01(\tR\aproject\x12\x12\n" +
	"\x04name\x18\x04 \x01(\tR\x04name\x12\x12\n" +
	"\x04hash\x18\x05 \x01(\tR\x04hash\x12\x14\n" +
	"\x05allow\x18\x06 \x03(\tR\x05allow\x12$\n" +
	"\x0erate_limit_rpm\x18\a \x01(\x05R\frateLimitRpm\x120\n" +
	"\x14monthly_token_budget\x18\b \x01(\x03R\x12monthlyTokenBudget\"L\n" +
	"\n" +
	"KeyRotated\x12\x19\n" +
	"\bnew_hash\x18\x01 \x01(\tR\anewHash\x12#\n" +
	"\rprevious_hash\x18\x02 \x01(\tR\fpreviousHash\"0\n" +
	"\vKeyDisabled\x12!\n" +
	"\fcurrent_hash\x18\x01 \x01(\tR\vcurrentHash\"+\n" +
	"\x13KeyAllowlistChanged\x12\x14\n" +
	"\x05allow\x18\x01 \x03(\tR\x05allow\"j\n" +
	"\x10KeyLimitsChanged\x12$\n" +
	"\x0erate_limit_rpm\x18\x01 \x01(\x05R\frateLimitRpm\x120\n" +
	"\x14monthly_token_budget\x18\x02 \x01(\x03R\x12monthlyTokenBudget\"\xe4\x02\n" +
	"\vApiKeyEvent\x127\n" +
	"\acreated\x18\x01 \x01(\v2\x1b.controlplane.v1.KeyCreatedH\x00R\acreated\x127\n" +
	"\arotated\x18\x02 \x01(\v2\x1b.controlplane.v1.KeyRotatedH\x00R\arotated\x12:\n" +
	"\bdisabled\x18\x03 \x01(\v2\x1c.controlplane.v1.KeyDisabledH\x00R\bdisabled\x12S\n" +
	"\x11allowlist_changed\x18\x04 \x01(\v2$.controlplane.v1.KeyAllowlistChangedH\x00R\x10allowlistChanged\x12J\n" +
	"\x0elimits_changed\x18\x05 \x01(\v2!.controlplane.v1.KeyLimitsChangedH\x00R\rlimitsChangedB\x06\n" +
	"\x04kindBAZ?github.com/laenenai/inferbus/api/controlplane/v1;controlplanev1b\x06proto3"

var (
	file_controlplane_v1_apikey_proto_rawDescOnce sync.Once
	file_controlplane_v1_apikey_proto_rawDescData []byte
)

func file_controlplane_v1_apikey_proto_rawDescGZIP() []byte {
	file_controlplane_v1_apikey_proto_rawDescOnce.Do(func() {
		file_controlplane_v1_apikey_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_controlplane_v1_apikey_proto_rawDesc), len(file_controlplane_v1_apikey_proto_rawDesc)))
	})
	return file_controlplane_v1_apikey_proto_rawDescData
}

var file_controlplane_v1_apikey_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_controlplane_v1_apikey_proto_goTypes = []any{
	(*ApiKey)(nil),              // 0: controlplane.v1.ApiKey
	(*CreateKey)(nil),           // 1: controlplane.v1.CreateKey
	(*RotateKey)(nil),           // 2: controlplane.v1.RotateKey
	(*DisableKey)(nil),          // 3: controlplane.v1.DisableKey
	(*SetAllowlist)(nil),        // 4: controlplane.v1.SetAllowlist
	(*SetLimits)(nil),           // 5: controlplane.v1.SetLimits
	(*ApiKeyCommand)(nil),       // 6: controlplane.v1.ApiKeyCommand
	(*KeyCreated)(nil),          // 7: controlplane.v1.KeyCreated
	(*KeyRotated)(nil),          // 8: controlplane.v1.KeyRotated
	(*KeyDisabled)(nil),         // 9: controlplane.v1.KeyDisabled
	(*KeyAllowlistChanged)(nil), // 10: controlplane.v1.KeyAllowlistChanged
	(*KeyLimitsChanged)(nil),    // 11: controlplane.v1.KeyLimitsChanged
	(*ApiKeyEvent)(nil),         // 12: controlplane.v1.ApiKeyEvent
}
var file_controlplane_v1_apikey_proto_depIdxs = []int32{
	1,  // 0: controlplane.v1.ApiKeyCommand.create:type_name -> controlplane.v1.CreateKey
	2,  // 1: controlplane.v1.ApiKeyCommand.rotate:type_name -> controlplane.v1.RotateKey
	3,  // 2: controlplane.v1.ApiKeyCommand.disable:type_name -> controlplane.v1.DisableKey
	4,  // 3: controlplane.v1.ApiKeyCommand.set_allowlist:type_name -> controlplane.v1.SetAllowlist
	5,  // 4: controlplane.v1.ApiKeyCommand.set_limits:type_name -> controlplane.v1.SetLimits
	7,  // 5: controlplane.v1.ApiKeyEvent.created:type_name -> controlplane.v1.KeyCreated
	8,  // 6: controlplane.v1.ApiKeyEvent.rotated:type_name -> controlplane.v1.KeyRotated
	9,  // 7: controlplane.v1.ApiKeyEvent.disabled:type_name -> controlplane.v1.KeyDisabled
	10, // 8: controlplane.v1.ApiKeyEvent.allowlist_changed:type_name -> controlplane.v1.KeyAllowlistChanged
	11, // 9: controlplane.v1.ApiKeyEvent.limits_changed:type_name -> controlplane.v1.KeyLimitsChanged
	10, // [10:10] is the sub-list for method output_type
	10, // [10:10] is the sub-list for method input_type
	10, // [10:10] is the sub-list for extension type_name
	10, // [10:10] is the sub-list for extension extendee
	0,  // [0:10] is the sub-list for field type_name
}

func init() { file_controlplane_v1_apikey_proto_init() }
func file_controlplane_v1_apikey_proto_init() {
	if File_controlplane_v1_apikey_proto != nil {
		return
	}
	file_controlplane_v1_apikey_proto_msgTypes[6].OneofWrappers = []any{
		(*ApiKeyCommand_Create)(nil),
		(*ApiKeyCommand_Rotate)(nil),
		(*ApiKeyCommand_Disable)(nil),
		(*ApiKeyCommand_SetAllowlist)(nil),
		(*ApiKeyCommand_SetLimits)(nil),
	}
	file_controlplane_v1_apikey_proto_msgTypes[12].OneofWrappers = []any{
		(*ApiKeyEvent_Created)(nil),
		(*ApiKeyEvent_Rotated)(nil),
		(*ApiKeyEvent_Disabled)(nil),
		(*ApiKeyEvent_AllowlistChanged)(nil),
		(*ApiKeyEvent_LimitsChanged)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_controlplane_v1_apikey_proto_rawDesc), len(file_controlplane_v1_apikey_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_controlplane_v1_apikey_proto_goTypes,
		DependencyIndexes: file_controlplane_v1_apikey_proto_depIdxs,
		MessageInfos:      file_controlplane_v1_apikey_proto_msgTypes,
	}.Build()
	File_controlplane_v1_apikey_proto = out.File
	file_controlplane_v1_apikey_proto_goTypes = nil
	file_controlplane_v1_apikey_proto_depIdxs = nil
}
