// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: controlplane/v1/org.proto

package controlplanev1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Project is a named, archivable unit within an Org.
type Project struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Archived      bool                   `protobuf:"varint,3,opt,name=archived,proto3" json:"archived,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Project) Reset() {
	*x = Project{}
	mi := &file_controlplane_v1_org_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Project) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Project) ProtoMessage() {}

func (x *Project) ProtoReflect() protoreflect.Message {
	mi := &file_controlplane_v1_org_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Project.ProtoReflect.Descriptor instead.
func (*Project) Descriptor() ([]byte, []int) {
	return file_controlplane_v1_org_proto_rawDescGZIP(), []int{0}
}

func (x *Project) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Project) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Project) GetArchived() bool {
	if x != nil {
		return x.Archived
	}
	return false
}

// Org is the aggregate state for one organization: its members (sub ->
// owner|admin|viewer) and its projects.
type Org struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Id    string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name  string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	// sub -> owner|admin|viewer
	Members       map[string]string   `protobuf:"bytes,3,rep,name=members,proto3" json:"members,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Projects      map[string]*Project `protobuf:"bytes,4,rep,name=projects,proto3" json:"projects,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Org) Reset() {
	*x = Org{}
	mi := &file_controlplane_v1_org_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Org) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Org) ProtoMessage() {}

func (x *Org) ProtoReflect() protoreflect.Message {
	mi := &file_controlplane_v1_org_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Org.ProtoReflect.Descriptor instead.
func (*Org) Descriptor() ([]byte, []int) {
	return file_controlplane_v1_org_proto_rawDescGZIP(), []int{1}
}

func (x *Org) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Org) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Org) GetMembers() map[string]string {
	if x != nil {
		return x.Members
	}
	return nil
}

func (x *Org) GetProjects() map[string]*Project {
	if x != nil {
		return x.Projects
	}
	return nil
}

type CreateOrg struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	OwnerSub      string                 `protobuf:"bytes,3,opt,name=owner_sub,json=ownerSub,proto3" json:"owner_sub,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateOrg) Reset() {
	*x = CreateOrg{}
	mi := &file_controlplane_v1_org_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateOrg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateOrg) ProtoMessage() {}

func (x *CreateOrg) ProtoReflect() protoreflect.Message {
	mi := &file_controlplane_v1_org_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateOrg.ProtoReflect.Descriptor instead.
func (*CreateOrg) Descriptor() ([]byte, []int) {
	return file_controlplane_v1_org_proto_rawDescGZIP(), []int{2}
}

func (x *CreateOrg) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *CreateOrg) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateOrg) GetOwnerSub() string {
	if x != nil {
		return x.OwnerSub
	}
	return ""
}

type RenameOrg struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RenameOrg) Reset() {
	*x = RenameOrg{}
	mi := &file_controlplane_v1_org_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RenameOrg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RenameOrg) ProtoMessage() {}

func (x *RenameOrg) ProtoReflect() protoreflect.Message {
	mi := &file_controlplane_v1_org_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RenameOrg.ProtoReflect.Descriptor instead.
func (*RenameOrg) Descriptor() ([]byte, []int) {
	return file_controlplane_v1_org_proto_rawDescGZIP(), []int{3}
}

func (x *RenameOrg) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type UpsertMember struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Sub           string                 `protobuf:"bytes,1,opt,name=sub,proto3" json:"sub,omitempty"`
	Role          string                 `protobuf:"bytes,2,opt,name=role,proto3" json:"role,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpsertMember) Reset() {
	*x = UpsertMember{}
	mi := &file_controlplane_v1_org_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpsertMember) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpsertMember) ProtoMessage() {}

func (x *UpsertMember) ProtoReflect() protoreflect.Message {
	mi := &file_controlplane_v1_org_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpsertMember.ProtoReflect.Descriptor instead.
func (*UpsertMember) Descriptor() ([]byte, []int) {
	return file_controlplane_v1_org_proto_rawDescGZIP(), []int{4}
}

func (x *UpsertMember) GetSub() string {
	if x != nil {
		return x.Sub
	}
	return ""
}

func (x *UpsertMember) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

type RemoveMember struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Sub           string                 `protobuf:"bytes,1,opt,name=sub,proto3" json:"sub,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveMember) Reset() {
	*x = RemoveMember{}
	mi := &file_controlplane_v1_org_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveMember) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveMember) ProtoMessage() {}

func (x *RemoveMember) ProtoReflect() protoreflect.Message {
	mi := &file_controlplane_v1_org_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveMember.ProtoReflect.Descriptor instead.
func (*RemoveMember) Descriptor() ([]byte, []int) {
	return file_controlplane_v1_org_proto_rawDescGZIP(), []int{5}
}

func (x *RemoveMember) GetSub() string {
	if x != nil {
		return x.Sub
	}
	return ""
}

type CreateProject struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateProject) Reset() {
	*x = CreateProject{}
	mi := &file_controlplane_v1_org_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateProject) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateProject) ProtoMessage() {}

func (x *CreateProject) ProtoReflect() protoreflect.Message {
	mi := &file_controlplane_v1_org_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateProject.ProtoReflect.Descriptor instead.
func (*CreateProject) Descriptor() ([]byte, []int) {
	return file_controlplane_v1_org_proto_rawDescGZIP(), []int{6}
}

func (x *CreateProject) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *CreateProject) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type ArchiveProject struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ArchiveProject) Reset() {
	*x = ArchiveProject{}
	mi := &file_controlplane_v1_org_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ArchiveProject) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ArchiveProject) ProtoMessage() {}

func (x *ArchiveProject) ProtoReflect() protoreflect.Message {
	mi := &file_controlplane_v1_org_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ArchiveProject.ProtoReflect.Descriptor instead.
func (*ArchiveProject) Descriptor() ([]byte, []int) {
	return file_controlplane_v1_org_proto_rawDescGZIP(), []int{7}
}

func (x *ArchiveProject) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type OrgCommand struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Kind:
	//
	//	*OrgCommand_Create
	//	*OrgCommand_Rename
	//	*OrgCommand_UpsertMember
	//	*OrgCommand_RemoveMember
	//	*OrgCommand_CreateProject
	//	*OrgCommand_ArchiveProject
	Kind          isOrgCommand_Kind `protobuf_oneof:"kind"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OrgCommand) Reset() {
	*x = OrgCommand{}
	mi := &file_controlplane_v1_org_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrgCommand) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrgCommand) ProtoMessage() {}

func (x *OrgCommand) ProtoReflect() protoreflect.Message {
	mi := &file_controlplane_v1_org_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrgCommand.ProtoReflect.Descriptor instead.
func (*OrgCommand) Descriptor() ([]byte, []int) {
	return file_controlplane_v1_org_proto_rawDescGZIP(), []int{8}
}

func (x *OrgCommand) GetKind() isOrgCommand_Kind {
	if x != nil {
		return x.Kind
	}
	return nil
}

func (x *OrgCommand) GetCreate() *CreateOrg {
	if x != nil {
		if x, ok := x.Kind.(*OrgCommand_Create); ok {
			return x.Create
		}
	}
	return nil
}

func (x *OrgCommand) GetRename() *RenameOrg {
	if x != nil {
		if x, ok := x.Kind.(*OrgCommand_Rename); ok {
			return x.Rename
		}
	}
	return nil
}

func (x *OrgCommand) GetUpsertMember() *UpsertMember {
	if x != nil {
		if x, ok := x.Kind.(*OrgCommand_UpsertMember); ok {
			return x.UpsertMember
		}
	}
	return nil
}

func (x *OrgCommand) GetRemoveMember() *RemoveMember {
	if x != nil {
		if x, ok := x.Kind.(*OrgCommand_RemoveMember); ok {
			return x.RemoveMember
		}
	}
	return nil
}

func (x *OrgCommand) GetCreateProject() *CreateProject {
	if x != nil {
		if x, ok := x.Kind.(*OrgCommand_CreateProject); ok {
			return x.CreateProject
		}
	}
	return nil
}

func (x *OrgCommand) GetArchiveProject() *ArchiveProject {
	if x != nil {
		if x, ok := x.Kind.(*OrgCommand_ArchiveProject); ok {
			return x.ArchiveProject
		}
	}
	return nil
}

type isOrgCommand_Kind interface {
	isOrgCommand_Kind()
}

type OrgCommand_Create struct {
	Create *CreateOrg `protobuf:"bytes,1,opt,name=create,proto3,oneof"`
}

type OrgCommand_Rename struct {
	Rename *RenameOrg `protobuf:"bytes,2,opt,name=rename,proto3,oneof"`
}

type OrgCommand_UpsertMember struct {
	UpsertMember *UpsertMember `protobuf:"bytes,3,opt,name=upsert_member,json=upsertMember,proto3,oneof"`
}

type OrgCommand_RemoveMember struct {
	RemoveMember *RemoveMember `protobuf:"bytes,4,opt,name=remove_member,json=removeMember,proto3,oneof"`
}

type OrgCommand_CreateProject struct {
	CreateProject *CreateProject `protobuf:"bytes,5,opt,name=create_project,json=createProject,proto3,oneof"`
}

type OrgCommand_ArchiveProject struct {
	ArchiveProject *ArchiveProject `protobuf:"bytes,6,opt,name=archive_project,json=archiveProject,proto3,oneof"`
}

func (*OrgCommand_Create) isOrgCommand_Kind() {}

func (*OrgCommand_Rename) isOrgCommand_Kind() {}

func (*OrgCommand_UpsertMember) isOrgCommand_Kind() {}

func (*OrgCommand_RemoveMember) isOrgCommand_Kind() {}

func (*OrgCommand_CreateProject) isOrgCommand_Kind() {}

func (*OrgCommand_ArchiveProject) isOrgCommand_Kind() {}

type OrgCreated struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	OwnerSub      string                 `protobuf:"bytes,3,opt,name=owner_sub,json=ownerSub,proto3" json:"owner_sub,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OrgCreated) Reset() {
	*x = OrgCreated{}
	mi := &file_controlplane_v1_org_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrgCreated) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrgCreated) ProtoMessage() {}

func (x *OrgCreated) ProtoReflect() protoreflect.Message {
	mi := &file_controlplane_v1_org_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrgCreated.ProtoReflect.Descriptor instead.
func (*OrgCreated) Descriptor() ([]byte, []int) {
	return file_controlplane_v1_org_proto_rawDescGZIP(), []int{9}
}

func (x *OrgCreated) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *OrgCreated) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *OrgCreated) GetOwnerSub() string {
	if x != nil {
		return x.OwnerSub
	}
	return ""
}

type OrgRenamed struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OrgRenamed) Reset() {
	*x = OrgRenamed{}
	mi := &file_controlplane_v1_org_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrgRenamed) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrgRenamed) ProtoMessage() {}

func (x *OrgRenamed) ProtoReflect() protoreflect.Message {
	mi := &file_controlplane_v1_org_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrgRenamed.ProtoReflect.Descriptor instead.
func (*OrgRenamed) Descriptor() ([]byte, []int) {
	return file_controlplane_v1_org_proto_rawDescGZIP(), []int{10}
}

func (x *OrgRenamed) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type MemberUpserted struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Sub           string                 `protobuf:"bytes,1,opt,name=sub,proto3" json:"sub,omitempty"`
	Role          string                 `protobuf:"bytes,2,opt,name=role,proto3" json:"role,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MemberUpserted) Reset() {
	*x = MemberUpserted{}
	mi := &file_controlplane_v1_org_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MemberUpserted) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MemberUpserted) ProtoMessage() {}

func (x *MemberUpserted) ProtoReflect() protoreflect.Message {
	mi := &file_controlplane_v1_org_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MemberUpserted.ProtoReflect.Descriptor instead.
func (*MemberUpserted) Descriptor() ([]byte, []int) {
	return file_controlplane_v1_org_proto_rawDescGZIP(), []int{11}
}

func (x *MemberUpserted) GetSub() string {
	if x != nil {
		return x.Sub
	}
	return ""
}

func (x *MemberUpserted) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

type MemberRemoved struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Sub           string                 `protobuf:"bytes,1,opt,name=sub,proto3" json:"sub,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MemberRemoved) Reset() {
	*x = MemberRemoved{}
	mi := &file_controlplane_v1_org_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MemberRemoved) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MemberRemoved) ProtoMessage() {}

func (x *MemberRemoved) ProtoReflect() protoreflect.Message {
	mi := &file_controlplane_v1_org_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MemberRemoved.ProtoReflect.Descriptor instead.
func (*MemberRemoved) Descriptor() ([]byte, []int) {
	return file_controlplane_v1_org_proto_rawDescGZIP(), []int{12}
}

func (x *MemberRemoved) GetSub() string {
	if x != nil {
		return x.Sub
	}
	return ""
}

type ProjectCreated struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProjectCreated) Reset() {
	*x = ProjectCreated{}
	mi := &file_controlplane_v1_org_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProjectCreated) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProjectCreated) ProtoMessage() {}

func (x *ProjectCreated) ProtoReflect() protoreflect.Message {
	mi := &file_controlplane_v1_org_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProjectCreated.ProtoReflect.Descriptor instead.
func (*ProjectCreated) Descriptor() ([]byte, []int) {
	return file_controlplane_v1_org_proto_rawDescGZIP(), []int{13}
}

func (x *ProjectCreated) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ProjectCreated) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type ProjectArchived struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProjectArchived) Reset() {
	*x = ProjectArchived{}
	mi := &file_controlplane_v1_org_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProjectArchived) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProjectArchived) ProtoMessage() {}

func (x *ProjectArchived) ProtoReflect() protoreflect.Message {
	mi := &file_controlplane_v1_org_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProjectArchived.ProtoReflect.Descriptor instead.
func (*ProjectArchived) Descriptor() ([]byte, []int) {
	return file_controlplane_v1_org_proto_rawDescGZIP(), []int{14}
}

func (x *ProjectArchived) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type OrgEvent struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Kind:
	//
	//	*OrgEvent_Created
	//	*OrgEvent_Renamed
	//	*OrgEvent_MemberUpserted
	//	*OrgEvent_MemberRemoved
	//	*OrgEvent_ProjectCreated
	//	*OrgEvent_ProjectArchived
	Kind          isOrgEvent_Kind `protobuf_oneof:"kind"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OrgEvent) Reset() {
	*x = OrgEvent{}
	mi := &file_controlplane_v1_org_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrgEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrgEvent) ProtoMessage() {}

func (x *OrgEvent) ProtoReflect() protoreflect.Message {
	mi := &file_controlplane_v1_org_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrgEvent.ProtoReflect.Descriptor instead.
func (*OrgEvent) Descriptor() ([]byte, []int) {
	return file_controlplane_v1_org_proto_rawDescGZIP(), []int{15}
}

func (x *OrgEvent) GetKind() isOrgEvent_Kind {
	if x != nil {
		return x.Kind
	}
	return nil
}

func (x *OrgEvent) GetCreated() *OrgCreated {
	if x != nil {
		if x, ok := x.Kind.(*OrgEvent_Created); ok {
			return x.Created
		}
	}
	return nil
}

func (x *OrgEvent) GetRenamed() *OrgRenamed {
	if x != nil {
		if x, ok := x.Kind.(*OrgEvent_Renamed); ok {
			return x.Renamed
		}
	}
	return nil
}

func (x *OrgEvent) GetMemberUpserted() *MemberUpserted {
	if x != nil {
		if x, ok := x.Kind.(*OrgEvent_MemberUpserted); ok {
			return x.MemberUpserted
		}
	}
	return nil
}

func (x *OrgEvent) GetMemberRemoved() *MemberRemoved {
	if x != nil {
		if x, ok := x.Kind.(*OrgEvent_MemberRemoved); ok {
			return x.MemberRemoved
		}
	}
	return nil
}

func (x *OrgEvent) GetProjectCreated() *ProjectCreated {
	if x != nil {
		if x, ok := x.Kind.(*OrgEvent_ProjectCreated); ok {
			return x.ProjectCreated
		}
	}
	return nil
}

func (x *OrgEvent) GetProjectArchived() *ProjectArchived {
	if x != nil {
		if x, ok := x.Kind.(*OrgEvent_ProjectArchived); ok {
			return x.ProjectArchived
		}
	}
	return nil
}

type isOrgEvent_Kind interface {
	isOrgEvent_Kind()
}

type OrgEvent_Created struct {
	Created *OrgCreated `protobuf:"bytes,1,opt,name=created,proto3,oneof"`
}

type OrgEvent_Renamed struct {
	Renamed *OrgRenamed `protobuf:"bytes,2,opt,name=renamed,proto3,oneof"`
}

type OrgEvent_MemberUpserted struct {
	MemberUpserted *MemberUpserted `protobuf:"bytes,3,opt,name=member_upserted,json=memberUpserted,proto3,oneof"`
}

type OrgEvent_MemberRemoved struct {
	MemberRemoved *MemberRemoved `protobuf:"bytes,4,opt,name=member_removed,json=memberRemoved,proto3,oneof"`
}

type OrgEvent_ProjectCreated struct {
	ProjectCreated *ProjectCreated `protobuf:"bytes,5,opt,name=project_created,json=projectCreated,proto3,oneof"`
}

type OrgEvent_ProjectArchived struct {
	ProjectArchived *ProjectArchived `protobuf:"bytes,6,opt,name=project_archived,json=projectArchived,proto3,oneof"`
}

func (*OrgEvent_Created) isOrgEvent_Kind() {}

func (*OrgEvent_Renamed) isOrgEvent_Kind() {}

func (*OrgEvent_MemberUpserted) isOrgEvent_Kind() {}

func (*OrgEvent_MemberRemoved) isOrgEvent_Kind() {}

func (*OrgEvent_ProjectCreated) isOrgEvent_Kind() {}

func (*OrgEvent_ProjectArchived) isOrgEvent_Kind() {}

var File_controlplane_v1_org_proto protoreflect.FileDescriptor

const file_controlplane_v1_org_proto_rawDesc = "" +
	"\n" +
	"\x19controlplane/v1/org.proto\x12\x0fcontrolplane.v1\"I\n" +
	"\aProject\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x1a\n" +
	"\barchived\x18\x03 \x01(\bR\barchived\"\xb9\x02\n" +
	"\x03Org\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12;\n" +
	"\amembers\x18\x03 \x03(\v2!.controlplane.v1.Org.MembersEntryR\amembers\x12>\n" +
	"\bprojects\x18\x04 \x03(\v2\".controlplane.v1.Org.ProjectsEntryR\bprojects\x1a:\n" +
	"\fMembersEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\x1aU\n" +
	"\rProjectsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12.\n" +
	"\x05value\x18\x02 \x01(\v2\x18.controlplane.v1.ProjectR\x05value:\x028\x01\"L\n" +
	"\tCreateOrg\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x1b\n" +
	"\towner_sub\x18\x03 \x01(\tR\bownerSub\"\x1f\n" +
	"\tRenameOrg\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\"4\n" +
	"\fUpsertMember\x12\x10\n" +
	"\x03sub\x18\x01 \x01(\tR\x03sub\x12\x12\n" +
	"\x04role\x18\x02 \x01(\tR\x04role\" \n" +
	"\fRemoveMember\x12\x10\n" +
	"\x03sub\x18\x01 \x01(\tR\x03sub\"3\n" +
	"\rCreateProject\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\" \n" +
	"\x0eArchiveProject\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"\xa1\x03\n" +
	"\n" +
	"OrgCommand\x124\n" +
	"\x06create\x18\x01 \x01(\v2\x1a.controlplane.v1.CreateOrgH\x00R\x06create\x124\n" +
	"\x06rename\x18\x02 \x01(\v2\x1a.controlplane.v1.RenameOrgH\x00R\x06rename\x12D\n" +
	"\rupsert_member\x18\x03 \x01(\v2\x1d.controlplane.v1.UpsertMemberH\x00R\fupsertMember\x12D\n" +
	"\rremove_member\x18\x04 \x01(\v2\x1d.controlplane.v1.RemoveMemberH\x00R\fremoveMember\x12G\n" +
	"\x0ecreate_project\x18\x05 \x01(\v2\x1e.controlplane.v1.CreateProjectH\x00R\rcreateProject\x12J\n" +
	"\x0farchive_project\x18\x06 \x01(\v2\x1f.controlplane.v1.ArchiveProjectH\x00R\x0earchiveProjectB\x06\n" +
	"\x04kind\"M\n" +
	"\n" +
	"OrgCreated\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x1b\n" +
	"\towner_sub\x18\x03 \x01(\tR\bownerSub\" \n" +
	"\n" +
	"OrgRenamed\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\"6\n" +
	"\x0eMemberUpserted\x12\x10\n" +
	"\x03sub\x18\x01 \x01(\tR\x03sub\x12\x12\n" +
	"\x04role\x18\x02 \x01(\tR\x04role\"!\n" +
	"\rMemberRemoved\x12\x10\n" +
	"\x03sub\x18\x01 \x01(\tR\x03sub\"4\n" +
	"\x0eProjectCreated\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\"!\n" +
	"\x0fProjectArchived\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"\xb4\x03\n" +
	"\bOrgEvent\x127\n" +
	"\acreated\x18\x01 \x01(\v2\x1b.controlplane.v1.OrgCreatedH\x00R\acreated\x127\n" +
	"\arenamed\x18\x02 \x01(\v2\x1b.controlplane.v1.OrgRenamedH\x00R\arenamed\x12J\n" +
	"\x0fmember_upserted\x18\x03 \x01(\v2\x1f.controlplane.v1.MemberUpsertedH\x00R\x0ememberUpserted\x12G\n" +
	"\x0emember_removed\x18\x04 \x01(\v2\x1e.controlplane.v1.MemberRemovedH\x00R\rmemberRemoved\x12J\n" +
	"\x0fproject_created\x18\x05 \x01(\v2\x1f.controlplane.v1.ProjectCreatedH\x00R\x0eprojectCreated\x12M\n" +
	"\x10project_archived\x18\x06 \x01(\v2 .controlplane.v1.ProjectArchivedH\x00R\x0fprojectArchivedB\x06\n" +
	"\x04kindBAZ?github.com/laenenai/inferbus/api/controlplane/v1;controlplanev1b\x06proto3"

var (
	file_controlplane_v1_org_proto_rawDescOnce sync.Once
	file_controlplane_v1_org_proto_rawDescData []byte
)

func file_controlplane_v1_org_proto_rawDescGZIP() []byte {
	file_controlplane_v1_org_proto_rawDescOnce.Do(func() {
		file_controlplane_v1_org_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_controlplane_v1_org_proto_rawDesc), len(file_controlplane_v1_org_proto_rawDesc)))
	})
	return file_controlplane_v1_org_proto_rawDescData
}

var file_controlplane_v1_org_proto_msgTypes = make([]protoimpl.MessageInfo, 18)
var file_controlplane_v1_org_proto_goTypes = []any{
	(*Project)(nil),         // 0: controlplane.v1.Project
	(*Org)(nil),             // 1: controlplane.v1.Org
	(*CreateOrg)(nil),       // 2: controlplane.v1.CreateOrg
	(*RenameOrg)(nil),       // 3: controlplane.v1.RenameOrg
	(*UpsertMember)(nil),    // 4: controlplane.v1.UpsertMember
	(*RemoveMember)(nil),    // 5: controlplane.v1.RemoveMember
	(*CreateProject)(nil),   // 6: controlplane.v1.CreateProject
	(*ArchiveProject)(nil),  // 7: controlplane.v1.ArchiveProject
	(*OrgCommand)(nil),      // 8: controlplane.v1.OrgCommand
	(*OrgCreated)(nil),      // 9: controlplane.v1.OrgCreated
	(*OrgRenamed)(nil),      // 10: controlplane.v1.OrgRenamed
	(*MemberUpserted)(nil),  // 11: controlplane.v1.MemberUpserted
	(*MemberRemoved)(nil),   // 12: controlplane.v1.MemberRemoved
	(*ProjectCreated)(nil),  // 13: controlplane.v1.ProjectCreated
	(*ProjectArchived)(nil), // 14: controlplane.v1.ProjectArchived
	(*OrgEvent)(nil),        // 15: controlplane.v1.OrgEvent
	nil,                     // 16: controlplane.v1.Org.MembersEntry
	nil,                     // 17: controlplane.v1.Org.ProjectsEntry
}
var file_controlplane_v1_org_proto_depIdxs = []int32{
	16, // 0: controlplane.v1.Org.members:type_name -> controlplane.v1.Org.MembersEntry
	17, // 1: controlplane.v1.Org.projects:type_name -> controlplane.v1.Org.ProjectsEntry
	2,  // 2: controlplane.v1.OrgCommand.create:type_name -> controlplane.v1.CreateOrg
	3,  // 3: controlplane.v1.OrgCommand.rename:type_name -> controlplane.v1.RenameOrg
	4,  // 4: controlplane.v1.OrgCommand.upsert_member:type_name -> controlplane.v1.UpsertMember
	5,  // 5: controlplane.v1.OrgCommand.remove_member:type_name -> controlplane.v1.RemoveMember
	6,  // 6: controlplane.v1.OrgCommand.create_project:type_name -> controlplane.v1.CreateProject
	7,  // 7: controlplane.v1.OrgCommand.archive_project:type_name -> controlplane.v1.ArchiveProject
	9,  // 8: controlplane.v1.OrgEvent.created:type_name -> controlplane.v1.OrgCreated
	10, // 9: controlplane.v1.OrgEvent.renamed:type_name -> controlplane.v1.OrgRenamed
	11, // 10: controlplane.v1.OrgEvent.member_upserted:type_name -> controlplane.v1.MemberUpserted
	12, // 11: controlplane.v1.OrgEvent.member_removed:type_name -> controlplane.v1.MemberRemoved
	13, // 12: controlplane.v1.OrgEvent.project_created:type_name -> controlplane.v1.ProjectCreated
	14, // 13: controlplane.v1.OrgEvent.project_archived:type_name -> controlplane.v1.ProjectArchived
	0,  // 14: controlplane.v1.Org.ProjectsEntry.value:type_name -> controlplane.v1.Project
	15, // [15:15] is the sub-list for method output_type
	15, // [15:15] is the sub-list for method input_type
	15, // [15:15] is the sub-list for extension type_name
	15, // [15:15] is the sub-list for extension extendee
	0,  // [0:15] is the sub-list for field type_name
}

func init() { file_controlplane_v1_org_proto_init() }
func file_controlplane_v1_org_proto_init() {
	if File_controlplane_v1_org_proto != nil {
		return
	}
	file_controlplane_v1_org_proto_msgTypes[8].OneofWrappers = []any{
		(*OrgCommand_Create)(nil),
		(*OrgCommand_Rename)(nil),
		(*OrgCommand_UpsertMember)(nil),
		(*OrgCommand_RemoveMember)(nil),
		(*OrgCommand_CreateProject)(nil),
		(*OrgCommand_ArchiveProject)(nil),
	}
	file_controlplane_v1_org_proto_msgTypes[15].OneofWrappers = []any{
		(*OrgEvent_Created)(nil),
		(*OrgEvent_Renamed)(nil),
		(*OrgEvent_MemberUpserted)(nil),
		(*OrgEvent_MemberRemoved)(nil),
		(*OrgEvent_ProjectCreated)(nil),
		(*OrgEvent_ProjectArchived)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_controlplane_v1_org_proto_rawDesc), len(file_controlplane_v1_org_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   18,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_controlplane_v1_org_proto_goTypes,
		DependencyIndexes: file_controlplane_v1_org_proto_depIdxs,
		MessageInfos:      file_controlplane_v1_org_proto_msgTypes,
	}.Build()
	File_controlplane_v1_org_proto = out.File
	file_controlplane_v1_org_proto_goTypes = nil
	file_controlplane_v1_org_proto_depIdxs = nil
}
